@Service02_HostAddress = http://localhost:5109
### USER 112233
GET {{Service02_HostAddress}}/api/event2/112233/127.0.0.1
Accept: application/json
###
GET {{Service02_HostAddress}}/api/event/112233/127.0.0.2




### HOST 127.0.0.1
GET {{Service02_HostAddress}}/api/event/122233/127.0.0.1
###
GET {{Service02_HostAddress}}/api/event/132233/127.0.0.1
###
GET {{Service02_HostAddress}}/api/event/142233/127.0.0.1

###
GET {{Service02_HostAddress}}/api/user/127.181.0.203
###
GET {{Service02_HostAddress}}/api/user/127.0.0
###
GET {{Service02_HostAddress}}/api/user/127.0.0.2

###
GET {{Service02_HostAddress}}/api/ip/112233

###
GET {{Service02_HostAddress}}/api/connection/112233
###
GET {{Service02_HostAddress}}/api/connection/112233/127.0.0.2